version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - vol_postgres:/var/lib/postgresql/data
    restart: always
volumes:
  vol_postgres:
