version: '3.8'

services:
  nestjs:
    container_name: nestjs-app
    image: oruj91/nestjs-graphql
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TYPEORM_SYNC=${TYPEORM_SYNC}
      - TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}
      - TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRE_SECONDS=${AUTH_JWT_TOKEN_EXPIRE_SECONDS}
      - AUTH_CONFIRM_URL=${AUTH_CONFIRM_URL}
      - AWS_MAIL_ENDPOINT=${AWS_MAIL_ENDPOINT}
      - AWS_MAIL_USER=${AWS_MAIL_USER}
      - AWS_MAIL_PASSWORD=${AWS_MAIL_PASSWORD}
      - AWS_MAIL_FROM=${AWS_MAIL_FROM}
    command: pnpm start:prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
